#!/usr/bin/env python3

import argparse
import logging
import os
import os.path
import sys
import traceback

from decimal import Decimal

sys.path.insert(0, os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..")))
import mango  # nopep8

# We explicitly want argument parsing to be outside the main try-except block because some arguments
# (like --help) will cause an exit, which our except: block traps.
parser = argparse.ArgumentParser(description="Buys an SPL token in a Serum market.")
mango.ContextBuilder.add_command_line_parameters(parser)
mango.Wallet.add_command_line_parameters(parser)
parser.add_argument("--symbol", type=str, required=True, help="market symbol to buy (e.g. ETH/USDC)")
parser.add_argument("--quantity", type=Decimal, required=True, help="quantity of token to buy")
parser.add_argument("--adjustment-factor", type=Decimal, default=Decimal("0.05"),
                    help="factor by which to adjust the BUY price (akin to maximum slippage)")
parser.add_argument("--wait", action="store_true", default=False,
                    help="wait until the transaction is confirmed")
parser.add_argument("--dry-run", action="store_true", default=False,
                    help="runs as read-only and does not perform any transactions")
args: argparse.Namespace = mango.parse_args(parser)

try:
    context = mango.ContextBuilder.from_command_line_parameters(args)
    wallet = mango.Wallet.from_command_line_parameters_or_raise(args)

    adjustment_factor = args.adjustment_factor

    logging.info(f"Wallet address: {wallet.address}")

    if args.dry_run:
        trade_executor: mango.TradeExecutor = mango.NullTradeExecutor()
    else:
        trade_executor = mango.ImmediateTradeExecutor(context, wallet, None, adjustment_factor)

    order = trade_executor.buy(args.symbol, args.quantity)
    logging.info(f"Buy completed for {order}")
except Exception as exception:
    logging.critical(f"Buy stopped because of exception: {exception} - {traceback.format_exc()}")
except:
    logging.critical(f"Buy stopped because of uncatchable error: {traceback.format_exc()}")
